--1. The total revenue generated by male vs. female customers.

select gender, SUM(purchase_amount) as Revenue
from customer
group by gender;


--2. Customers used a discount but still spent more than the average purchase amount.

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase;

--3. The top 5 products with the highest average review rating.

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


--4. The average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


--6. The top 5 products having the highest percentage of purchases with discounts applied

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segement
from customer
)

select customer_segement, count(*) as "Numbers of Customers"
from customer_type
group by customer_segement;
 

--8. The top 3 most purchased products within each category.

with item_count as (
select category, 
item_purchased,
COUNT(customer_id) as total_orders
ROW_NUMBER() over (
)


--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;



--10. The revenue contribution of each age group? 

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

